import { useEffect, useRef, useState } from 'react';
import { loadData, localDate, mealTotals, nutritionUnit, nutritionValues, ingredientQuantity, freshData, validateBackup, STORAGE_KEY, type AppData, type Ingredient, type Meal, type NutritionFood, type Nutrients, type UsualMeal } from './domain';
import MealEditor, { LabelForm } from './MealEditor';
import { useJournal } from './useJournal';
import { mergeDeviceJournal, supabase } from './cloud';
import { api, Icon, MacroLine, Modal, newId, number, nutrientKeys, nutrientNames, ProteinNote } from './ui';

type Config = { geminiConfigured: boolean; model: string; dailyLimit: number; remainingToday: number | null; nutritionMode: string };
type Parsed = { title: string; items: Omit<Ingredient, 'id'>[]; checks: string[] };
type View = 'journal' | 'usual' | 'settings';
function formatDate(date: string, options: Intl.DateTimeFormatOptions = { weekday: 'long', month: 'long', day: 'numeric' }) { return new Intl.DateTimeFormat(undefined, options).format(new Date(`${date}T12:00:00`)); }
function download(content: string, filename: string) {
  const url = URL.createObjectURL(new Blob([content], { type: 'application/json' }));
  const link = document.createElement('a'); link.href = url; link.download = filename; link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function Summary({ totals, targets, onTargets }: { totals: Nutrients; targets: AppData['targets']; onTargets: () => void }) {
  const target = targets.calories;
  return <section className="daily-summary panel" aria-label="Daily nutrition totals">
    <div className="calorie-summary"><div className="section-heading"><span className="summary-label">Daily energy</span><span className="badge subtle">kcal</span></div><div className="calorie-value">{number(totals.calories)}<span>{target ? `/ ${number(target)}` : 'kcal'}</span></div><div className="progress-track" role={target ? 'progressbar' : undefined} aria-label="Calorie target progress" aria-valuenow={target ? Math.min(target, Math.round(totals.calories)) : undefined} aria-valuemin={target ? 0 : undefined} aria-valuemax={target ? target : undefined}><span style={{ width: target ? `${Math.min(100, totals.calories / target * 100)}%` : '0%' }} /></div><p className="small muted">{target ? `${number(Math.abs(target - totals.calories))} kcal ${totals.calories > target ? 'above target' : 'remaining'}` : <button className="text-button small" onClick={onTargets}>Set your own daily targets <Icon name="arrow" size={14} /></button>}</p></div>
    <div className="macro-summary">{(['protein', 'carbs', 'fat'] as const).map(key => <div className="macro-stat" key={key}><span className="summary-label"><i className={`dot ${key}`} />{nutrientNames[key]}</span><div className="macro-value">{number(totals[key])}<span>g</span></div><div className={`progress-track ${key}`}><span style={{ width: targets[key] ? `${Math.min(100, totals[key] / targets[key]! * 100)}%` : '0%' }} /></div><span className="small muted">{targets[key] ? `of ${number(targets[key]!)} g target` : 'No target set'}</span>{Boolean(targets[key]) && <span className="small macro-balance">{number(Math.abs(targets[key]! - totals[key]))} g {totals[key] > targets[key]! ? 'above target' : 'remaining'}</span>}</div>)}</div>
  </section>;
}

function UsualCard({ usual, onLog, onEdit, onDelete, compact = false }: { usual: UsualMeal; onLog: () => void; onEdit: () => void; onDelete?: () => void; compact?: boolean }) {
  const total = mealTotals(usual.items);
  return <article className={`usual-card ${compact ? 'compact' : 'panel'}`}><div className="usual-heading"><span className="food-symbol"><Icon name="plate" /></span><div><h3>{usual.title}</h3><p className="small muted">{usual.items.length} {usual.items.length === 1 ? 'ingredient' : 'ingredients'} · {number(total.calories)} kcal</p></div></div>{!compact && <><p className="small muted ingredients-list">{usual.items.map(item => `${item.name} (${number(ingredientQuantity(item)!)} ${nutritionUnit(item.food!)})`).join(' · ')}</p><MacroLine totals={total} /></>}<div className="usual-actions"><button className="button secondary" onClick={onLog}><Icon name="plus" size={16} />Log meal</button><button className="text-button" onClick={onEdit}>Edit first</button>{onDelete && <button className="text-button danger" onClick={onDelete}>Delete</button>}</div></article>;
}

export default function App({ userId, email }: { userId?: string; email?: string }) {
  const journal = useJournal(userId);
  const { data, storageError, loading, loadError, saving, unsaved } = journal;
  const cloudMode = Boolean(userId);
  const [view, setView] = useState<View>(() => ['usual', 'settings'].includes(location.hash.slice(1)) ? location.hash.slice(1) as View : 'journal');
  const [date, setDate] = useState(localDate);
  const [today, setToday] = useState(localDate);
  const [config, setConfig] = useState<Config | null>(null);
  const [configError, setConfigError] = useState('');
  const [description, setDescription] = useState('');
  const [parsing, setParsing] = useState(false);
  const [entryError, setEntryError] = useState('');
  const [draft, setDraft] = useState<Meal | null>(null);
  const [mode, setMode] = useState<'meal' | 'usual'>('meal');
  const [toast, setToast] = useState('');
  const [savedMeal, setSavedMeal] = useState<Meal | null>(null);
  const [labelOpen, setLabelOpen] = useState(false);
  const [restore, setRestore] = useState<AppData | null>(null);
  const [restoreSource, setRestoreSource] = useState<'backup' | 'device'>('backup');
  const [settingsError, setSettingsError] = useState('');
  const [confirmDelete, setConfirmDelete] = useState<{ title: string; run: () => Promise<void> } | null>(null);
  const entryRef = useRef<HTMLTextAreaElement>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const previousToday = useRef(localDate());
  const parseRevision = useRef(0);

  useEffect(() => { void refreshConfig(); const hash = () => setView(['usual', 'settings'].includes(location.hash.slice(1)) ? location.hash.slice(1) as View : 'journal'); window.addEventListener('hashchange', hash); return () => window.removeEventListener('hashchange', hash); }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 6000); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => {
    const onVisible = () => {
      if (document.visibilityState !== 'visible') return;
      const nextToday = localDate();
      const oldToday = previousToday.current;
      if (nextToday !== oldToday) { setToday(nextToday); setDate(current => current === oldToday ? nextToday : current); previousToday.current = nextToday; setToast('Hari baru! Log hari ini mulai dari nol. Meal sebelumnya tetap tersimpan.'); }
    };
    const timer = window.setInterval(onVisible, 30000);
    document.addEventListener('visibilitychange', onVisible); window.addEventListener('focus', onVisible);
    return () => { window.clearInterval(timer); document.removeEventListener('visibilitychange', onVisible); window.removeEventListener('focus', onVisible); };
  }, []);

  async function refreshConfig() { try { setConfig(await api<Config>('/api/config')); setConfigError(''); } catch (err) { setConfigError((err as Error).message); } }
  function navigate(next: View) { parseRevision.current += 1; setView(next); location.hash = next === 'journal' ? '' : next; }
  async function commit(next: AppData, recovery = false) {
    try { await journal.commit(next, recovery); return true; }
    catch (err) { setToast((err as Error).message); return false; }
  }
  async function addLabel(label: NutritionFood) { const saved = await commit({ ...data, labels: [...data.labels, label] }); if (saved) setToast('Package label saved for next time.'); return saved; }
  function editMeal(meal: Meal, nextMode: 'meal' | 'usual' = 'meal') { parseRevision.current += 1; setMode(nextMode); setDraft(structuredClone(meal)); window.scrollTo({ top: 0 }); }
  async function logUsual(usual: UsualMeal) {
    const meal: Meal = { ...structuredClone(usual), id: newId(), date, createdAt: new Date().toISOString() };
    if (await commit({ ...data, meals: [...data.meals, meal] })) { setToast(`${usual.title} logged for ${formatDate(date, { month: 'short', day: 'numeric' })}.`); navigate('journal'); }
  }
  async function saveDraft() {
    if (!draft) return;
    if (mode === 'usual') {
      const { date: _date, ...usual } = draft;
      if (!await commit({ ...data, usualMeals: data.usualMeals.map(existing => existing.id === usual.id ? usual : existing) })) return;
      setToast('Usual meal template updated.'); setDraft(null); return;
    }
    const meal = { ...draft, title: draft.title.trim() };
    const meals = data.meals.some(existing => existing.id === meal.id) ? data.meals.map(existing => existing.id === meal.id ? meal : existing) : [...data.meals, meal];
    if (await commit({ ...data, meals })) { setDate(meal.date); setDraft(null); setSavedMeal(meal); setDescription(''); setToast('Meal saved.'); navigate('journal'); }
  }
  async function saveUsual(meal: Meal) {
    const { date: _date, ...usual } = structuredClone(meal);
    usual.id = newId(); usual.createdAt = new Date().toISOString();
    if (await commit({ ...data, usualMeals: [...data.usualMeals, usual] })) { setSavedMeal(null); setToast('Added to your usual meals.'); }
  }
  async function parseMeal() {
    if (!description.trim() || parsing) return;
    setParsing(true); setEntryError('');
    const revision = ++parseRevision.current;
    const submittedText = description.trim();
    const submittedDate = date;
    try {
      const result = await api<Parsed>('/api/parse', { description: submittedText });
      if (revision !== parseRevision.current) return;
      const meal: Meal = { id: newId(), date: submittedDate, title: result.title, items: result.items.map(item => ({ ...item, id: newId() })), checks: result.checks, createdAt: new Date().toISOString() };
      editMeal(meal); setDescription('');
    } catch (err) { if (revision === parseRevision.current) setEntryError((err as Error).message); }
    finally { setParsing(false); void refreshConfig(); }
  }
  const meals = data.meals.filter(meal => meal.date === date).sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  const totals = mealTotals(meals.flatMap(meal => meal.items));
  function moveDate(offset: number) { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + offset); setDate(localDate(next)); }

  if (loading || loadError) return <main className="account-page"><a href="#" className="brand">portion.</a><section className="panel account-panel"><h1>{loading ? 'Opening your journal…' : 'Your journal needs a connection.'}</h1><p className="muted" role={loadError ? 'alert' : 'status'}>{loadError || 'Loading your saved meals and targets from your account.'}</p>{loadError && <button className="button secondary" onClick={() => void journal.reload()}>Retry cloud connection</button>}<button className="text-button" onClick={() => void supabase?.auth.signOut()}>Sign out</button></section></main>;

  return <>
    <header className="app-header"><div className="header-inner"><a className="brand" href="#" onClick={() => navigate('journal')}><span className="brand-mark"><Icon name="plate" size={25} /></span>portion<span className="brand-period">.</span></a><nav aria-label="Main navigation">{([['journal', 'journal', 'Journal'], ['usual', 'bookmark', 'Usual meals'], ['settings', 'settings', 'Settings']] as const).map(([next, icon, label]) => <a href={next === 'journal' ? '#' : `#${next}`} className={view === next && !draft ? 'active' : ''} aria-current={view === next && !draft ? 'page' : undefined} key={next} onClick={event => { if (saving) { event.preventDefault(); return; } if (draft && !confirm('Discard your unsaved meal edits?')) event.preventDefault(); else { setDraft(null); navigate(next); } }}><Icon name={icon} size={18} />{label}</a>)}</nav><span className="device-note"><Icon name="lock" size={14} />{cloudMode ? 'Your account. Your journal.' : 'Your device. Your journal.'}</span></div></header>
    <main className="app-main" inert={saving}>
      {unsaved && <div className="notice error-message" role="alert"><div>A cloud save was not confirmed. Your unsaved version is available to export.<div className="inline-actions"><button className="text-button" onClick={() => download(JSON.stringify(unsaved, null, 2), `portion-unsaved-${today}.json`)}>Export unsaved version</button><button className="text-button" onClick={() => { if (confirm('Reload the cloud journal? Export the unsaved version first if you need it. Unsaved meal edits will be closed.')) { setDraft(null); setDescription(''); setLabelOpen(false); setRestore(null); parseRevision.current += 1; void journal.reload(); } }}>Reload cloud journal</button></div></div></div>}
      {storageError && <div className="notice error-message" role="alert"><Icon name="info" /><div>{storageError}<div className="inline-actions"><button className="text-button" onClick={() => { try { download(localStorage.getItem(STORAGE_KEY) || '', `portion-recovery-${today}.json`); } catch { setToast('Browser storage is unavailable.'); } }}>Export preserved data</button><button className="text-button" onClick={() => navigate('settings')}>Restore backup</button></div></div></div>}
      {draft ? <MealEditor cloudMode={cloudMode} draft={draft} mode={mode} targets={data.targets} dayTotals={mealTotals(data.meals.filter(meal => meal.date === draft.date && meal.id !== draft.id).flatMap(meal => meal.items))} labels={data.labels} onChange={setDraft} onCancel={() => { if (confirm('Discard your unsaved meal edits?')) setDraft(null); }} onSave={saveDraft} onLabel={addLabel} /> : view === 'journal' ? <>
        <div className="page-heading"><div><p className="eyebrow">Your daily food journal</p><h1>{date === today && !meals.length ? "Hai! Siap track hari ini?" : "Your food journal."}</h1><p className="muted">Ceritain makanannya. Kita cek porsi, sumber, dan macros bareng.</p></div><div className="date-controls"><button className="icon-button" onClick={() => moveDate(-1)} aria-label="Previous day"><Icon name="left" size={18} /></button><label className="date-label"><span>{date === today ? 'Today' : formatDate(date, { month: 'short', day: 'numeric' })}</span><input type="date" value={date} aria-label="Log date" onChange={event => { if (event.target.value) setDate(event.target.value); }} /></label><button className="icon-button" onClick={() => moveDate(1)} aria-label="Next day"><Icon name="right" size={18} /></button>{date !== today && <button className="text-button" onClick={() => setDate(today)}>Today</button>}</div></div>
        <Summary totals={totals} targets={data.targets} onTargets={() => navigate('settings')} />
        <div className="journal-grid"><div className="journal-primary">
          <section className="panel entry-panel"><div className="section-heading"><div className="heading-with-icon"><span className="entry-icon"><Icon name="spark" /></span><h2>What’s on your plate?</h2></div><span className="small muted">{formatDate(date, { month: 'short', day: 'numeric' })}</span></div><p className="muted small">Boleh Bahasa Indonesia or English. Bisa pakai gelas, mangkuk, atau potong. AI memperkirakan porsinya; kamu bisa edit sebelum save.</p><form onSubmit={event => { event.preventDefault(); void parseMeal(); }}><textarea disabled={parsing} ref={entryRef} aria-label="Describe your meal" value={description} onChange={event => setDescription(event.target.value)} placeholder="Aku minum 1 gelas caffe latte dan makan 1 mangkuk mie ayam…" maxLength={4000} rows={4} /><div className="entry-footer"><span className="small muted"><Icon name="check" size={14} />Review & edit before saving</span><button className="button primary" disabled={parsing || !description.trim() || !config?.geminiConfigured}><Icon name={parsing ? 'spark' : 'arrow'} size={18} />{parsing ? 'Interpreting meal…' : 'Review meal'}</button></div></form>
            {entryError && <p className="error-message" role="alert">{entryError}</p>}
            {configError ? <div className="setup-note"><p className="small">{configError}</p><button className="text-button" onClick={() => void refreshConfig()}>Retry connection</button></div> : config && !config.geminiConfigured ? <div className="setup-note"><Icon name="info" size={18} /><div><strong className="small">Connect Gemini to describe meals</strong><p className="small muted">Add your key to the server’s .env file, then restart. You can use saved labels and manual entry now.</p><button className="text-button small" onClick={() => navigate('settings')}>View setup instructions <Icon name="arrow" size={13} /></button></div></div> : <p className="privacy-caption small muted">Meal text is sent to Google for AI estimates. You can also choose database or package-label values. <a href="#settings" onClick={() => navigate('settings')}>Privacy details</a></p>}
            <ProteinNote protein={totals.protein} target={data.targets.protein} mealProtein={meals.length ? mealTotals(meals[meals.length - 1].items).protein : undefined} />
          </section>
          <section className="meal-section"><div className="section-heading"><h2>{date === today ? 'Today’s meals' : 'Meals for this day'} <span className="count">{meals.length}</span></h2><button className="text-button" onClick={() => editMeal({ id: newId(), date, title: 'My meal', items: [], checks: [], createdAt: new Date().toISOString() })}><Icon name="plus" size={16} />Add manually</button></div>
            {savedMeal && <div className="saved-prompt"><span><Icon name="check" size={17} />Meal saved. Have this often?</span><button className="text-button" onClick={() => saveUsual(savedMeal)}><Icon name="bookmark" size={15} />Save as usual meal</button><button className="icon-button" onClick={() => setSavedMeal(null)} aria-label="Dismiss usual meal offer"><Icon name="close" size={14} /></button></div>}
            {meals.length === 0 ? <div className="panel empty-meals"><div className="empty-plate"><Icon name="plate" size={37} /></div><h3>A fresh page for your day.</h3><p className="muted small">Your meals will appear here once you log them.<br />Start with what’s on your plate.</p><button className="text-button" onClick={() => { entryRef.current?.focus(); entryRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }}>Add your first meal <Icon name="arrow" size={15} /></button></div> : <div className="meal-list">{meals.map(meal => <article className="panel meal-card" key={meal.id}><div className="meal-card-top"><span className="food-symbol"><Icon name="plate" /></span><div className="meal-name"><h3>{meal.title}</h3><p className="small muted">{meal.items.map(item => item.name).join(' · ')}</p></div><strong className="meal-energy">{number(mealTotals(meal.items).calories)}<span className="small muted"> kcal</span></strong></div><MacroLine totals={mealTotals(meal.items)} /><div className="meal-card-actions"><button className="text-button" onClick={() => editMeal(meal)}>Review & edit</button><button className="text-button" onClick={() => saveUsual(meal)}><Icon name="bookmark" size={14} />Save as usual</button><button className="text-button danger" onClick={() => setConfirmDelete({ title: meal.title, run: async () => { if (await commit({ ...data, meals: data.meals.filter(existing => existing.id !== meal.id) })) { if (savedMeal?.id === meal.id) setSavedMeal(null); setToast('Meal deleted.'); } } })}>Delete</button></div></article>)}</div>}
          </section>
        </div><aside className="journal-sidebar"><section className="panel usual-panel"><div className="section-heading"><div className="heading-with-icon"><Icon name="bookmark" size={19} /><h2>Your usuals</h2></div><a className="text-button small" href="#usual">View all <Icon name="arrow" size={13} /></a></div>{data.usualMeals.length ? data.usualMeals.slice(0, 3).map(usual => <UsualCard key={usual.id} usual={usual} compact onLog={() => logUsual(usual)} onEdit={() => editMeal({ ...usual, date, id: newId(), createdAt: new Date().toISOString() })} />) : <div className="usual-empty"><span className="usual-illustration"><Icon name="bookmark" size={28} /></span><h3>Good meals, on repeat.</h3><p className="small muted">Save a confirmed meal as a usual.<br />Next time, log it with one tap.</p></div>}</section><section className="quiet-note"><span className="eyebrow">Review before saving.</span><h3>Asumsinya selalu terlihat.</h3><p className="small muted">AI estimates portions and macros, including local dishes. Check the assumptions or choose a database or package label for a closer match.</p><div className="note-divider" /><p className="small muted"><Icon name="lock" size={14} />{cloudMode ? 'Your confirmed journal is saved to your account. Export a backup whenever you like.' : 'Your food log stays in this browser. Export a backup whenever you like.'}</p><a href="#settings" className="text-button small">Manage your data <Icon name="arrow" size={14} /></a></section></aside></div>
      </> : view === 'usual' ? <><div className="page-heading"><div><p className="eyebrow">Your everyday favourites</p><h1>Good meals, on repeat.</h1><p className="muted">Ingredient templates you can log in a tap or make your own.</p></div><label className="small">Log to date<input type="date" value={date} onChange={event => { if (event.target.value) setDate(event.target.value); }} /></label></div>{data.usualMeals.length ? <div className="usual-grid">{data.usualMeals.map(usual => <UsualCard key={usual.id} usual={usual} onLog={() => logUsual(usual)} onEdit={() => editMeal({ ...usual, date, id: newId(), createdAt: new Date().toISOString() })} onDelete={() => setConfirmDelete({ title: usual.title, run: async () => { if (await commit({ ...data, usualMeals: data.usualMeals.filter(existing => existing.id !== usual.id) })) setToast('Usual meal deleted.'); } })} />)}</div> : <div className="panel empty-meals"><Icon name="bookmark" size={35} /><h3>Your favourites start with a meal.</h3><p className="small muted">After reviewing and saving a meal, choose “Save as usual meal”.</p><button className="button primary" onClick={() => navigate('journal')}>Go to journal <Icon name="arrow" /></button></div>}{data.usualMeals.length > 0 && <section className="template-list"><h2>Manage ingredient templates</h2><p className="small muted">Change a usual’s ingredients, portion sizes, and cooking assumptions for future use.</p>{data.usualMeals.map(usual => <div className="template-row" key={usual.id}><span>{usual.title}</span><button className="text-button" onClick={() => editMeal({ ...usual, date }, 'usual')}>Edit template</button></div>)}</section>}</> : <>
        <div className="page-heading"><div><p className="eyebrow">Make it yours</p><h1>Your journal, your way.</h1><p className="muted">Optional targets, reusable food labels, and control of your data.</p></div></div>
        <div className="settings-grid">{cloudMode && <section className="panel settings-panel account-settings"><div className="section-heading"><h2>Your account</h2><span className="badge">Cloud journal</span></div><p className="account-email">{email}</p><p className="small muted">Confirmed meals, usuals, package labels, and targets are saved to your private Supabase journal. Sign in on another device to continue.</p><div className="inline-actions"><button className="button secondary" onClick={() => { parseRevision.current += 1; void journal.reload(); }}>Refresh journal</button><button className="text-button" onClick={async () => { if ((description || unsaved) && !confirm('Sign out with unsaved changes? Export the unsaved version first if you need it.')) return; const result = await supabase?.auth.signOut(); if (result?.error) setToast('Sign-out failed. Please try again.'); }}>Sign out</button></div><div className="device-import"><h3>Bring your device journal</h3><p className="small muted">Import meals, usuals, and labels saved in this browser before accounts. Existing account copies with the same ID are kept. Device data remains available as a backup.</p><button className="button secondary" onClick={() => { try { const device = loadData(); if (!device.meals.length && !device.usualMeals.length && !device.labels.length) { setToast('No meals, usuals, or labels were found on this site address. Export a backup from the old localhost app and restore it here.'); return; } setRestoreSource('device'); setRestore(mergeDeviceJournal(data, device)); } catch (error) { setToast((error as Error).message); } }}>Review device import</button></div></section>}<section className="panel settings-panel"><h2>Daily targets</h2><p className="small muted">Set your own daily goals. New accounts start at 0; zero or blank means no target.</p><button className="text-button target-preset" onClick={async () => { if (await commit({ ...data, targets: freshData().targets })) setToast('Daily targets reset to zero.'); }}>Reset targets to zero</button><form key={JSON.stringify(data.targets)} onSubmit={async event => {
          event.preventDefault(); const form = new FormData(event.currentTarget); const targets: AppData['targets'] = {};
          for (const key of nutrientKeys) { const value = String(form.get(key) || '').trim(); if (value) targets[key] = Number(value); }
          if (await commit({ ...data, targets })) setToast('Daily targets updated.');
        }}><div className="form-grid">{nutrientKeys.map(key => <label key={key}>{nutrientNames[key]} ({key === 'calories' ? 'kcal' : 'g'})<input name={key} type="number" inputMode="decimal" min="0" max="1000000" step="any" defaultValue={data.targets[key] ?? ''} placeholder="Optional" /></label>)}</div><button className="button primary">Save targets</button></form></section>
          <section className="panel settings-panel"><div className="section-heading"><h2>Package labels</h2><button className="text-button" onClick={() => setLabelOpen(true)}><Icon name="plus" size={16} />Add label</button></div><p className="small muted">Your own reliable source for a brand the database doesn’t know.</p>{data.labels.length === 0 ? <p className="small muted empty-labels">No saved labels yet.</p> : data.labels.map(label => <div className="label-row" key={label.id}><div><strong>{label.name}</strong><p className="small muted">{number(nutritionValues(label).calories)} kcal / 100 {nutritionUnit(label)}</p></div><button className="text-button danger" onClick={() => setConfirmDelete({ title: label.name, run: async () => { if (await commit({ ...data, labels: data.labels.filter(existing => existing.id !== label.id) })) setToast('Label removed. Logged meals keep their nutrition data.'); } })}>Delete</button></div>)}</section>
          <section className="panel settings-panel"><h2>Your data & backup</h2><p className="small muted">{cloudMode ? 'Your journal is saved to your account. Keep an exported backup too; Supabase Free does not include automatic database backups. Restoring a backup replaces this account’s journal after confirmation.' : 'Meals, templates, labels, and targets stay in this browser on this device. Clearing browser data removes the journal. Backups let you move it to another browser or device.'}</p><div className="backup-actions"><button className="button secondary" onClick={() => download(JSON.stringify(data, null, 2), `portion-backup-${today}.json`)}><Icon name="download" />Export backup</button><button className="button secondary" onClick={() => fileRef.current?.click()}>Restore backup</button><input ref={fileRef} className="visually-hidden" type="file" accept=".json,application/json" onChange={async event => {
            const file = event.target.files?.[0]; event.target.value = ''; if (!file) return;
            setSettingsError(''); setRestoreSource('backup'); try { if (file.size > 10 * 1024 * 1024) throw new Error('Choose a backup smaller than 10 MB.'); setRestore(validateBackup(JSON.parse(await file.text()))); } catch (err) { setSettingsError((err as Error).message); }
          }} /></div>{settingsError && <p role="alert" className="error-message">{settingsError}</p>}<p className="small muted">{cloudMode ? 'Cloud changes appear when you open or refresh the journal. Saves need a connection. If another device has changed the journal, reload it before saving. Usual meals and labels do not use Gemini.' : 'Keep the same address and port when returning to your journal; browser storage is specific to the site address. Usual meals and labels work without Gemini.'}</p></section>
          <section className="panel settings-panel setup-panel"><div className="section-heading"><h2>Gemini connection</h2><span className={`badge ${config?.geminiConfigured ? '' : 'subtle'}`}>{config?.geminiConfigured ? 'Key configured' : 'Setup needed'}</span></div><p className="small muted">{config?.model || 'gemini-2.5-flash-lite'} · {config?.dailyLimit ?? 20} parses per server day maximum. {config?.remainingToday !== null && config?.remainingToday !== undefined ? `${config.remainingToday} remaining.` : ''}</p><ol className="setup-steps"><li>Create a key in <a href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">Google AI Studio</a> for a project <strong>without active billing</strong>. Google’s project settings determine whether requests are free.</li><li>{cloudMode ? <>In Vercel’s project settings, set <code>GEMINI_API_KEY</code> as a server environment variable. Never give it a <code>VITE_</code> prefix.</> : <>Copy <code>.env.example</code> to <code>.env</code> in the project folder. Set <code>GEMINI_API_KEY</code> there. Never paste it into this app.</>}</li><li>{cloudMode ? <>Redeploy after changing environment variables. For local use, restart <code>npm run dev</code>.</> : <>Restart <code>npm run dev</code>, then check the connection below.</>}</li></ol><button className="button secondary" onClick={() => void refreshConfig()}>Check connection</button><p className="small muted">{cloudMode ? 'The key stays in the server environment. All hosted users share the durable daily safeguard, which resets at midnight UTC. Google’s quotas apply separately; there is no paid-service fallback.' : 'The key stays on the Node server. No model or paid-service fallback is used. The local safeguard resets with the server; Google’s quotas apply separately.'}</p><p className="small muted">AI estimates are filled in first. Optional database searches use USDA and Open Food Facts, with no Open Food Facts API key needed. Check the exact brand and flavor against your package. For regular use, get a <a href="https://fdc.nal.usda.gov/api-key-signup" target="_blank" rel="noreferrer">free USDA key</a> and set <code>USDA_API_KEY</code>. Without one, its shared DEMO_KEY allows just 30 requests/hour and 50/day per IP.</p></section>
          <section className="panel settings-panel privacy-panel"><h2>Where your meal goes</h2><p className="small muted">Portion uses a NutriTrack ID instruction for Indonesian food vocabulary, household portions, and approximate recipe nutrition. AI estimates are clearly labeled and can differ from the actual serving or brand. Targets and protein feedback are calculated on this device; your age, height, weight, and student profile are not sent to Google.</p><p className="small muted">Meal descriptions travel through the server to Google Gemini for parsing and nutrition estimation. Portion does not store or log raw descriptions on the server. Food names, brands, and preparation are sent to USDA or Open Food Facts for nutrition lookup. {cloudMode ? 'Supabase stores your sign-in details and confirmed structured food journal. Its row security restricts each journal to its owner. Vercel hosts the app and parsing endpoints.' : 'Your confirmed food log is stored on this device.'}</p><p className="small muted">Under Google’s unpaid-service terms, inputs and responses may be used to improve its products, and human reviewers may process them. Avoid sensitive or personal information in meal text. Terms depend on region and billing status; Google’s terms include age, supported-region, and professional/business-use requirements. Free-tier clients have additional restrictions for EEA, Switzerland, and UK users.</p><p className="small muted"><a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noreferrer">Google API terms</a> · <a href="https://ai.google.dev/gemini-api/docs/pricing" target="_blank" rel="noreferrer">Current free-tier pricing</a> · <a href="https://fdc.nal.usda.gov/api-guide/" target="_blank" rel="noreferrer">USDA data & terms</a> · <a href="https://world.openfoodfacts.org" target="_blank" rel="noreferrer">Open Food Facts</a> · <a href="https://opendatacommons.org/licenses/odbl/1-0/" target="_blank" rel="noreferrer">Open Food Facts data: ODbL</a></p></section>
        </div>
      </>}
      <footer className="app-footer"><span>Made for your everyday.</span><span><i className="status-dot" />{cloudMode ? 'Saved to your account' : 'Stored on this device'}</span></footer>
    </main>
    {saving && <div className="toast" role="status"><Icon name="lock" size={18} />{cloudMode ? 'Saving to your account…' : 'Saving journal…'}</div>}
    {!saving && toast && <div className="toast" role="status"><Icon name="info" size={18} /><span>{toast}</span><button className="icon-button" aria-label="Dismiss notification" onClick={() => setToast('')}><Icon name="close" size={16} /></button></div>}
    {labelOpen && <LabelForm onSave={addLabel} onClose={() => setLabelOpen(false)} />}
    {restore && <Modal title={restoreSource === 'device' ? 'Import your device journal?' : 'Restore this backup?'} onClose={() => setRestore(null)}><p>{restoreSource === 'device' ? 'After adding missing items, your account will contain' : 'This will replace your current journal with'} {restore.meals.length} meals, {restore.usualMeals.length} usual {restore.usualMeals.length === 1 ? 'meal' : 'meals'}, and {restore.labels.length} {restore.labels.length === 1 ? 'label' : 'labels'}.</p><p className="small muted">{restoreSource === 'device' ? 'Existing account copies with the same ID are kept. Your device journal remains unchanged.' : 'Export your current data first if you want to keep it.'}</p><button className="button primary full" onClick={async () => { if (await commit(restore, true)) { setRestore(null); setToast(restoreSource === 'device' ? 'Device journal imported.' : 'Backup restored.'); } }}>{restoreSource === 'device' ? 'Import device journal' : 'Replace journal & restore'}</button></Modal>}
    {confirmDelete && <Modal title="Delete this item?" onClose={() => setConfirmDelete(null)}><p>Remove “{confirmDelete.title}” from {cloudMode ? 'your account' : 'this device'}?</p><div className="inline-actions"><button className="button secondary" onClick={() => setConfirmDelete(null)}>Keep it</button><button className="button danger-button" onClick={async () => { await confirmDelete.run(); setConfirmDelete(null); }}>Delete</button></div></Modal>}
  </>;
}
